name: Build and Run Docker Container

on:
  push:
    branches:
      - main

jobs:
  build_and_run_docker:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    # SSH Key 값 출력
    - name: Print SSH Key for debugging
      run: echo ${{ secrets.SSH_KEY }}
    
    # GCP 서버에 SSH로 접속하여 이전에 실행 중이던 도커 컨테이너 중지 및 삭제 및 GitHub 레포지토리 업데이트
    - name: Stop and remove previous container and Update GitHub repository
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}  # GitHub Secrets에 저장된 GCP 서버의 IP 주소
        username: ${{ secrets.USERNAME }}  # GCP 서버의 유저명
        key: ${{ secrets.SSH_KEY }}  # GCP 서버에 접속하기 위한 SSH 키
        port: 22
        script: |
          docker stop civilwar_bot || true
          docker rm civilwar_bot || true
          sh deploy-ssh.sh  # deploy-ssh.sh 스크립트 실행
          docker build -t civilwar_bot .
          docker run --name civilwar_bot -d -v $(pwd):/app -p 80:8080 civilwar_bot
